export const API_ROUTES = {
    AUTH_ME: "/api/auth/me",
    LOGIN: "/api/auth/login",
    LOGOUT: "/api/auth/logout",
    FACILITY_SETTINGS: "/api/facility/settings",
    CARE_LEVELS: "/api/care-levels",
    STAFFING_RATIOS: "/api/staffing-ratios",
    RESIDENTS: "/api/residents",
    CARE_PLANS: "/api/care-plans",
    MEDICATIONS: "/api/medications",
    DOCTOR_SCHEDULES: "/api/doctor-schedules",
    EQUIPMENT_SUPPLIES: "/api/equipment-supplies",
    INCIDENT_SEVERITIES: "/api/incident-severities",
    SLA_CONFIGURATIONS: "/api/sla-configurations",
    DASHBOARD_NURSE: "/dashboard/nurse",
    DASHBOARD_DON: "/dashboard/don",
    DASHBOARD_CNA: "/dashboard/cna",
    DASHBOARD_SUMMARY: "/dashboard/summary",
} as const;
