export const APP_ROUTES = {
    LANDING: "/",
    DASHBOARD: "/dashboard",
    RESIDENTS: "/residents",
    RESIDENT_RECEPTION: "/residents/reception",
    DOCTOR_SCHEDULE: "/doctor-schedule",
    EMAR: "/emar",
    CARE_PLANS: "/care-plans",
    CREATE_CARE_PLAN: "/care-plans/new",
    CARE_PLAN: "/care-plans/:id",
    DON_REVIEW: "/care-plans/:id/review",
    IDT_ACKNOWLEDGMENT: "/care-plans/:id/acknowledge",
    LOGIN: "/login",
    REGISTER: "/login/register",
    FORGOT_PASSWORD: "/login/forgot-password",
    ENTER_NEW_PASSWORD: "/login/enter-new-password",
    SIGN_IN: "/sign-in",
    SIGN_UP: "/sign-up",
} as const;
